name: nikola
dependencies:
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- lxml=3.6.0=py35_0
- openssl=1.0.2h=1
- pip=8.1.2=py35_0
- python=3.5.1=5
- readline=6.2=2
- setuptools=23.0.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - argh==0.26.2
  - blinker==1.4
  - cloudpickle==0.2.1
  - docutils==0.12
  - doit==0.29.0
  - ghp-import2==1.0.1
  - husl==4.0.3
  - jinja2==2.8
  - logbook==1.0.0
  - mako==1.0.4
  - markupsafe==0.23
  - natsort==5.0.1
  - nikola==7.7.9
  - pathtools==0.1.2
  - pillow==3.3.0
  - pygments==2.1.3
  - pyinotify==0.9.6
  - pyrss2gen==1.1
  - python-dateutil==2.5.3
  - pyyaml==3.11
  - requests==2.10.0
  - six==1.10.0
  - unidecode==0.4.19
  - watchdog==0.8.3
  - webassets==0.11.1
  - ws4py==0.3.5
  - yapsy==1.11.223

